---
title: "objectif1"
author: "obj1"
date: "2023-11-13"
output: github_document
---
### chargement des librairies
```{r}
library(ggplot2)
library(dplyr)
```

### chargement des données
```{r}
amsterdam <- read.csv("data/amsterdam_weekends.csv")
athens <- read.csv("data/athens_weekends.csv")
barcelona <- read.csv("data/barcelona_weekends.csv")
berlin <- read.csv("data/berlin_weekends.csv")
budapest <- read.csv("data/budapest_weekends.csv")
lisbon <- read.csv("data/lisbon_weekends.csv")
london <- read.csv("data/london_weekends.csv")
paris <- read.csv("data/paris_weekends.csv")
rome <- read.csv("data/rome_weekends.csv")
vienna <- read.csv("data/vienna_weekends.csv")

cityList = list(amsterdam, athens, barcelona, berlin, budapest, lisbon, london, paris, rome, vienna)
colorVector = c("orange", "blue", "red", "yellow", "chartreuse1", "seagreen", "brown", "thistle","cadetblue1", "gold1")

combined_data <- bind_rows(cityList, .id = "city")
  
combined_data$city <- replace(combined_data$city, combined_data$city==1, "Amsterdam")
combined_data$city <- replace(combined_data$city, combined_data$city==2, "Athènes")
combined_data$city <- replace(combined_data$city, combined_data$city==3, "Barcelone")
combined_data$city <- replace(combined_data$city, combined_data$city==4, "Berlin")
combined_data$city <- replace(combined_data$city, combined_data$city==5, "Budapest")
combined_data$city <- replace(combined_data$city, combined_data$city==6, "Lisbonne")
combined_data$city <- replace(combined_data$city, combined_data$city==7, "Londres")
combined_data$city <- replace(combined_data$city, combined_data$city==8, "Paris")
combined_data$city <- replace(combined_data$city, combined_data$city==9, "Rome")
combined_data$city <- replace(combined_data$city, combined_data$city==10, "Vienne")

combined_data_by_density <- combined_data %>% arrange(factor(city, levels = c('Amsterdam', 'Berlin', 'Barcelone', 'Vienne', 'Budapest', 'Athènes', 'Lisbonne', 'Paris', 'Rome', 'Londres')))
```

###Graphe Ligne Combiné
```{r}
citiesPriceToDistComparison <- function(dataList, colorVector) {
  
  combined_plot <- ggplot(dataList, aes(x = dist, y = realSum, color = city)) +
    geom_line() +
    labs(
      title = "Prix des Airbnb en fonction de la distance au centre-ville",
      x = "Distance au centre-ville",
      y = "Prix total de l'annonce",
      color = "Ville"
    ) +
    scale_color_manual(values = colorVector) +
    theme_minimal()
  
  return(combined_plot)
}

citiesPriceToDistComparison(combined_data, colorVector)
```

###Graphe Densité pour plus de visibilité
```{r}
citiesPriceComparison <- function(dataList, colorVector) {
  
  combined_plot <- ggplot(dataList, aes(x = realSum, after_stat(count), fill = city)) +
    geom_density(position="stack") +
    labs(
      title = "Prix des Airbnb",
      x = "Prix total de l'annonce",
      color = "Ville"
    ) +
    scale_color_manual(values = colorVector) +
    theme_minimal() +
    xlim(0,2300)
  
  return(combined_plot)
}

citiesPriceComparison(combined_data_by_density, colorVector)
```

###creation de fonction pour automatiser le processus

```{r}
graphe<-function(data){
  
  line_chart<- ggplot(data,aes(x=dist, y=realSum))+
    geom_line(color="blue")+
    labs(title="Prix des Airbnb en fonction de la distance au
         centre-ville",
         x="Distance au centre-ville",
         y="Prix total de l'annonce") +
    theme_minimal()
  
  line_chart
  
}
```


```{r}
graphe(amsterdam)
graphe(athens)
```

###FONCTION 2 HS
```{r}
generate_airbnb_plots <- function(data) {
  # Charger la bibliothèque ggplot2
  library(ggplot2)

  # Créer un graphique en lignes avec ggplot
  line_chart <- ggplot(data, aes(x = dist, y = realSum, group = 1)) +
    geom_line(color = "blue") +
    labs(title = "Prix des Airbnb en fonction de la distance au centre-ville",
         x = "Distance au centre-ville",
         y = "Prix total de l'annonce") +
    theme_minimal()

  # Créer des graphiques de boxplots avec courbe de tendance pour chaque ville
  boxplots <- ggplot(data, aes(x = as.factor(dist), y = realSum, fill = as.factor(dist))) +
    geom_boxplot() +
    geom_point(position = position_jitter(width = 0.2), alpha = 0.7) +
    labs(title = "Boxplots avec Courbe de Tendance pour chaque ville",
         x = "Distance au centre-ville",
         y = "Prix total de l'annonce") +
    theme_minimal()

  # Afficher les graphiques
  line_chart
  boxplots
}


```


